<?php

require '../config/connection.php';

Class tarjetaPrincipalM {

    public function _construct() { /* Constructor */
    }
    
    function insertTCP($IdCliente,$contactAddress,$Agent,$Tmstmp,$IDENTIFICACIONTCP,$NOMBRE1TCP,$NOMBRE2TCP,$APELLIDO1TCP,$APELLIDO2TCP,$provinciaNacTCP,$ciudadNacTCP,$estadoCivilTCP,$generoTCP,$fecNacTCP,$emailTCP,$celTCP,$telfDom,$CUPOTCP,$pdpTCP,$estadoctaTCP,$nacionalidadTCP,$paisTCP,$contTCP,$provinciaDomTCP,$ciudadDomTCP,$tipoVivTCP,$cantonDomTCP,$parroquiaDomTCP,$principalDomTCP,$secundariaDomTCP,$numDomTCP,$sectorDomTCP,$refDomTCP,$provinciaTrabTCP,$ciudadTrabTCP,$cantonTrabTCP,$parroquiaTrabTCP,$principalTrabTCP,$secundariaTrabTCP,$numTrabTCP,$sectorTrabTCP,$refTrabTCP,$telfTrab,$situaLabTCP,$empresaTCP,$contratoTCP,$fechaIniTCP,$cargoTCP,$sueldoTCP,$gastosTCP,$negocioTCP,$ventasTCP,$costoTCP,$actEcoTCP,$gastosOpeTCP,$fechaIniNegTCP,$perRefTCP,$provinciaRefTCP,$ciudadRefTCP,$telfRefTCP,$relacionCliTCP,$lugarEntTCP,$dirEntTCP,$perContTCP,$telfContTCP,$horEntTCP,$equipFutTCP,$TipoTarjeta,$tipoOferta,$CODIGO_CAMPANIA,$cambioProdTCP, $subestatus1TCP, $subestatus2TCP) { //inserción de datos
        $sql = "INSERT INTO tcp(ContactId, ContactAddress, InteractionId, Agente, Tmstmp, Cedula, PrimerNombre,SegundoNombre, PrimerApellido, SegundoApellido, Nacionalidad, PaisNacimiento,ProvinciaNacimiento, CiudadNacimiento, EstadoCivil, Genero, FechaNacimiento, Email, Celular,Telefono, Cupo1, Cupo2, Cupo3, SeguroDesgravamen, EmisionEstadoCuenta, PaisDom,ObligadoContabilidad, ProvinciaDom, CiudadDom, TipoViviendaDom, CantonDom, ParroquiaDom,CallePrincipalDom, CalleSecundariaDom, NumeracionDom, BarrioSector, ReferenciaDom,SituaciónLaboral, NombreNegocio, FechaInicioNegocio, ActividadEconomica, VentasHonorariosMensuales,CostoVentas, GastosGenOperativos, NombreEmpresa, Contrato, Cargo, FechaInicioTrabajo, Sueldo,GastosFamiliares, ProvinciaTrab, CiudadTrab, CantonTrab, ParroquiaTrab, CallePrincipalTrab,CalleSecundariaTrab, NumeracionTrab, BarrioSectorTrab, ReferenciaTrab,telefonoTrab,NombreReferencia,PaisRef, ProvinciaRef, CiudadRef, TelefonoRef, RelacionClienteRef,LugarEntrega, DireccionEntrega,PersonaContacto, TelefonoContacto, HorarioEntrega, EquipoFutbolPreferencia,TipoTarjeta, CodigoCampania,OfertaSeleccionada, CambioProducto, estatus1, estatus2) "
            . "VALUES ('$IdCliente','$contactAddress','','$Agent','$Tmstmp','$IDENTIFICACIONTCP','$NOMBRE1TCP','$NOMBRE2TCP','$APELLIDO1TCP','$APELLIDO2TCP','$nacionalidadTCP','$paisTCP','$provinciaNacTCP','$ciudadNacTCP','$estadoCivilTCP','$generoTCP','$fecNacTCP','$emailTCP','$celTCP','$telfDom','$CUPOTCP','$CUPOTCP','$CUPOTCP','$pdpTCP','$estadoctaTCP','$nacionalidadTCP','$contTCP','$provinciaDomTCP','$ciudadDomTCP','$tipoVivTCP','$cantonDomTCP','$parroquiaDomTCP','$principalDomTCP','$secundariaDomTCP','$numDomTCP','$sectorDomTCP','$refDomTCP','$situaLabTCP','$negocioTCP','$fechaIniNegTCP','$actEcoTCP','$ventasTCP','$costoTCP','$gastosOpeTCP','$empresaTCP','$contratoTCP','$cargoTCP','$fechaIniTCP','$sueldoTCP','$gastosTCP','$provinciaTrabTCP','$ciudadTrabTCP','$cantonTrabTCP','$parroquiaTrabTCP','$principalTrabTCP','$secundariaTrabTCP','$numTrabTCP','$sectorTrabTCP','$refTrabTCP','$telfTrab','$perRefTCP','$paisTCP','$provinciaRefTCP','$ciudadRefTCP','$telfRefTCP','$relacionCliTCP','$lugarEntTCP','$dirEntTCP','$perContTCP','$telfContTCP','$horEntTCP','$equipFutTCP','$TipoTarjeta','$tipoOferta','$CODIGO_CAMPANIA','$cambioProdTCP','$subestatus1TCP','$subestatus2TCP')";
        return ejecutarConsulta1($sql);
    }
    
    function updateTCP($IdCliente,$contactAddress,$Agent,$Tmstmp,$IDENTIFICACIONTCP,$NOMBRE1TCP,$NOMBRE2TCP,$APELLIDO1TCP,$APELLIDO2TCP,$provinciaNacTCP,$ciudadNacTCP,$estadoCivilTCP,$generoTCP,$fecNacTCP,$emailTCP,$celTCP,$telfDom,$CUPOTCP,$pdpTCP,$estadoctaTCP,$nacionalidadTCP,$paisTCP,$contTCP,$provinciaDomTCP,$ciudadDomTCP,$tipoVivTCP,$cantonDomTCP,$parroquiaDomTCP,$principalDomTCP,$secundariaDomTCP,$numDomTCP,$sectorDomTCP,$refDomTCP,$provinciaTrabTCP,$ciudadTrabTCP,$cantonTrabTCP,$parroquiaTrabTCP,$principalTrabTCP,$secundariaTrabTCP,$numTrabTCP,$sectorTrabTCP,$refTrabTCP,$telfTrab,$situaLabTCP,$empresaTCP,$contratoTCP,$fechaIniTCP,$cargoTCP,$sueldoTCP,$gastosTCP,$negocioTCP,$ventasTCP,$costoTCP,$actEcoTCP,$gastosOpeTCP,$fechaIniNegTCP,$perRefTCP,$provinciaRefTCP,$ciudadRefTCP,$telfRefTCP,$relacionCliTCP,$lugarEntTCP,$dirEntTCP,$perContTCP,$telfContTCP,$horEntTCP,$equipFutTCP,$TipoTarjeta,$tipoOferta,$CODIGO_CAMPANIA,$cambioProdTCP, $subestatus1TCP, $subestatus2TCP) { //inserción de datos
        $sql = "UPDATE `tcp` SET `ContactAddress`='$contactAddress',`InteractionId`='',`Agente`='$Agent',`Tmstmp`='$Tmstmp',`Cedula`='$IDENTIFICACIONTCP',`PrimerNombre`='$NOMBRE1TCP',`SegundoNombre`='$NOMBRE2TCP',`PrimerApellido`='$APELLIDO1TCP',`SegundoApellido`='$APELLIDO2TCP',`Nacionalidad`='$nacionalidadTCP',`PaisNacimiento`='$paisTCP',`ProvinciaNacimiento`='$provinciaNacTCP',`CiudadNacimiento`='$ciudadNacTCP',`EstadoCivil`='$estadoCivilTCP',`Genero`='$generoTCP',`FechaNacimiento`='$fecNacTCP',`Email`='$emailTCP',`Celular`='$celTCP',`Telefono`='$telfDom',`Cupo1`='$CUPOTCP',`Cupo2`='$CUPOTCP',`Cupo3`='$CUPOTCP',`SeguroDesgravamen`='$pdpTCP',`EmisionEstadoCuenta`='$estadoctaTCP',`PaisDom`='$nacionalidadTCP',`ObligadoContabilidad`='$contTCP',`ProvinciaDom`='$provinciaDomTCP',`CiudadDom`='$ciudadDomTCP',`TipoViviendaDom`='$tipoVivTCP',`CantonDom`='$cantonDomTCP',`ParroquiaDom`='$parroquiaDomTCP',`CallePrincipalDom`='$principalDomTCP',`CalleSecundariaDom`='$secundariaDomTCP',`NumeracionDom`='$numDomTCP',`BarrioSector`='$sectorDomTCP',`ReferenciaDom`='$refDomTCP',`SituaciónLaboral`='$situaLabTCP',`NombreNegocio`='$negocioTCP',`FechaInicioNegocio`='$fechaIniNegTCP',`ActividadEconomica`='$actEcoTCP',`VentasHonorariosMensuales`='$ventasTCP',`CostoVentas`='$costoTCP',`GastosGenOperativos`='$gastosOpeTCP',`NombreEmpresa`='$empresaTCP',`Contrato`='$contratoTCP',`Cargo`='$cargoTCP',`FechaInicioTrabajo`='$fechaIniTCP',`Sueldo`='$sueldoTCP',`GastosFamiliares`='$gastosTCP',`ProvinciaTrab`='$provinciaTrabTCP',`CiudadTrab`='$ciudadTrabTCP',`CantonTrab`='$cantonTrabTCP',`ParroquiaTrab`='$parroquiaTrabTCP',`CallePrincipalTrab`='$principalTrabTCP',`CalleSecundariaTrab`='$secundariaTrabTCP',`NumeracionTrab`='$numTrabTCP',`BarrioSectorTrab`='$sectorTrabTCP',`ReferenciaTrab`='$refTrabTCP',`telefonoTrab`='$telfTrab',`NombreReferencia`='$perRefTCP',`PaisRef`='$paisTCP',`ProvinciaRef`='$provinciaRefTCP',`CiudadRef`='$ciudadRefTCP',`TelefonoRef`='$telfRefTCP',`RelacionClienteRef`='$relacionCliTCP',`LugarEntrega`='$lugarEntTCP',`DireccionEntrega`='$dirEntTCP',`PersonaContacto`='$perContTCP',`TelefonoContacto`='$telfContTCP',`HorarioEntrega`='$horEntTCP',`EquipoFutbolPreferencia`='$equipFutTCP',`TipoTarjeta`='$TipoTarjeta',`CodigoCampania`='$CODIGO_CAMPANIA',`OfertaSeleccionada`='$tipoOferta',`CambioProducto`='$cambioProdTCP',`estatus1`= '$subestatus1TCP',`estatus2`= '$subestatus2TCP' WHERE contactid = '$IdCliente' ";
        return ejecutarConsulta1($sql);
    }
}

?>